### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by lheagy** [ubcgif/2019-heagy-oldenburg-gji-dc-steel-cased-wells#2]
The current README is from the template repo. This should be replaced with the Title, Authors, Summary, Citation and image following the template. 

I like to edit the readme directly on github 
![image](https://github.com/ubcgif/2019-heagy-oldenburg-gji-dc-steel-cased-wells/assets/6361812/ee7cd878-aa47-411d-8cc9-60875e0220fa)

The below text provides a template

```
# Paper tile here

_Authors_

[https://doi.org/XXX](https://doi.org/XXX)

![thumbnail](./paper/thumbnail.png)

## Summary

Summary of the paper here (pulled from abstract/summary of paper) 

## Citation

Please include the formatted citation along with bibtex for the reference

```

**Comment by tetikshajain** [comment]
updated the README file and created a pull request for new thumbnail picture
