### ISSUE TITLE
moving figures 

### ISSUE THREAD

**Issue by lheagy** [ubcgif/2019-heagy-oldenburg-gji-dc-steel-cased-wells#3]
Currently, all of the figures are at the end of the paper (some journals require this for submission), but as a reader, it is much nicer to have the figures in context. 

To do this, we should move the figures from the end (in order) and put each after the first paragraph it is discussed in. For example the first figure is here 
https://github.com/ubcgif/2019-heagy-oldenburg-gji-dc-steel-cased-wells/blob/00d4214a9dfca16ce154b39cdbf976f1970dbf2b/paper/casingDCpaper.tex#L366

and it is first mentioned here `Figure \ref{fig:dc_discretization} demonstrates`... 
https://github.com/ubcgif/2019-heagy-oldenburg-gji-dc-steel-cased-wells/blob/00d4214a9dfca16ce154b39cdbf976f1970dbf2b/paper/casingDCpaper.tex#L77

So the `\input{figures/dc_discretization}` could be moved to line 78.

**Comment by tetikshajain** [comment]
moved figures and tables to the necessary line. commented out figures and tables mentioned at the end. if alignment is fine, I can delete it

**Comment by lheagy** [comment]
Thanks for updating this! That looks great. You can just leave the text there at the end as comments.
