### ISSUE TITLE
description

### ISSUE THREAD

**Issue by lheagy** [ubcgif/2019-heagy-oldenburg-gji-dc-steel-cased-wells#5]
One last request for this repository, would you mind adding a `description` to the `myst.yml` file (it can go right after the `title`). 

e.g. from the 2024 paper as an example: 
https://github.com/ubcgif/2024-heagy-etal-tle-future-of-applied-geophysics/blob/e5e75b9ceffe929ce775811f0f16638f49f88c3c/paper/myst.yml#L6

**Comment by tetikshajain** [comment]
added description. By mistake did it through the main branch though.
