### ISSUE TITLE
acknowledgements

### ISSUE THREAD

**Issue by lheagy** [ubcgif/2019-heagy-oldenburg-gji-dc-steel-cased-wells#6]
Right now, the template doesn't automatically pull out acknowledgements that are in between the begin / end acknowledgement in LaTeX: 

```
\begin{acknowledgments}

Acknowledgement here

\end{acknowledgments}
```

To have this show up, we should modify the latex and instead use a heading 
```
\section*{Acknowledgments}

Acknowledgement here
```

The `*` makes sure that we don't number that section. @tetikshajain: would you mind updating that in this repository and also taking a look at the others? Thanks so much!

**Comment by tetikshajain** [comment]
updated and created a pull request
